# 参考
# https://github.com/takanabe/github-actions-oidc-test/blob/main/.github/workflows/main.yml
name: Example
on:
  workflow_dispatch:
    inputs:
      aws_account_id:
        description: 'Your AWS account ID you deployed GitHub Acitons IAM role via Terraform'
        required: true
        default: 'YOU_AWS_ACCOUNT_ID'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - run: sleep 5 # there's still a race condition for now

      - name: Configure AWS
        run: |
          export AWS_ROLE_ARN=arn:aws:iam::${{ github.event.inputs.aws_account_id}}:role/GitHubReadOnlyAccess
          export AWS_WEB_IDENTITY_TOKEN_FILE=/tmp/awscreds
          export AWS_DEFAULT_REGION=ap-northeast-1

          echo AWS_WEB_IDENTITY_TOKEN_FILE=$AWS_WEB_IDENTITY_TOKEN_FILE >> $GITHUB_ENV
          echo AWS_ROLE_ARN=$AWS_ROLE_ARN >> $GITHUB_ENV
          echo AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION >> $GITHUB_ENV

          curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=sigstore" | jq -r '.value' > $AWS_WEB_IDENTITY_TOKEN_FILE
      - uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: "${{ env.AWS_ROLE_ARN }}"
          web-identity-token-file: "${{ env.AWS_WEB_IDENTITY_TOKEN_FILE }}"
          aws-region: "${{ env.AWS_DEFAULT_REGION }}"
          role-duration-seconds: 900
          role-session-name: GitHubActionsTestSession
      - run: aws sts get-caller-identity # just an example. why not deploy something?
